tplProjectName: mobilebuilder_tpl_7_8_0
â†“Menu [mobile.components.UIDynamicMenu-1604074900896]: ğŸ— mobileMenus/Menu.yaml
â†“VonageVideo [mobile.components.UISharedComponent-1604074988538]: ğŸ— mobileSharedComponents/VonageVideo.yaml
â†“Page [mobile.components.PageComponent-1604074906869]: ğŸ— mobilePages/Page.yaml